//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIQU.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QiQuEntities : DbContext
    {
        public QiQuEntities()
            : base("name=QiQuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_admin> t_admin { get; set; }
        public virtual DbSet<t_article> t_article { get; set; }
        public virtual DbSet<t_article_coll> t_article_coll { get; set; }
        public virtual DbSet<t_publish_record> t_publish_record { get; set; }
        public virtual DbSet<t_article_category> t_article_category { get; set; }
        public virtual DbSet<t_article_comments> t_article_comments { get; set; }
        public virtual DbSet<t_feedback> t_feedback { get; set; }
    }
}
