//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIQU.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_article_comments
    {
        public int id { get; set; }
        public int article_id { get; set; }
        public int user_id { get; set; }
        public int parent_id { get; set; }
        public string contents { get; set; }
        public System.DateTime create_time { get; set; }
        public int child_count { get; set; }
        public QIQU.Entity.CommentStatus status { get; set; }
        public string from_area { get; set; }
        public string from_ip { get; set; }
    }
}
